name: Render PPM

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ imagemagick

      - name: Build
        run: |
          cd raytracing_in_one_weekend
          g++ firstimage.cpp -o firstimage

      - name: Generate PPM
        run: |
          cd raytracing_in_one_weekend
          ./firstimage > firstimage.ppm

      - name: Convert to PNG
        run: |
          cd raytracing_in_one_weekend
          magick firstimage.ppm firstimage.png

      - name: Commit PNG
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add raytracing_in_one_weekend/firstimage.png
          git commit -m "Update render" || echo "No changes"
          git push

